import type { BuilderEquipment, Gw2Item } from "../../types/buildEditor";
import { fetchGw2Items } from "./gw2Api";

export const BUILDER_ITEM_CACHE_KEY = "entropy.builder.items.v1";

export interface BuilderNamedChoice {
  label: string;
  id?: number;
}

// These are the exact text choices supported by the installed AxiCode format.
// Keeping the codec vocabulary here makes the editor searchable without
// silently exporting a label that the binary format cannot preserve.
export const BUILDER_RELIC_CHOICES = [
  "Relic of Agony", "Relic of Akeem", "Relic of Altruism", "Relic of Antitoxin",
  "Relic of Atrocity", "Relic of Bava Nisos", "Relic of Bloodstone", "Relic of Castora",
  "Relic of Cerus", "Relic of Dagda", "Relic of Durability", "Relic of Dwayna",
  "Relic of Evasion", "Relic of Febe", "Relic of Fire", "Relic of Fireworks",
  "Relic of Fog", "Relic of Geysers", "Relic of Isgarren", "Relic of Karakosa",
  "Relic of Leadership", "Relic of Lyhr", "Relic of Mabon", "Relic of Mercy",
  "Relic of Mistburn", "Relic of Mosyn", "Relic of Mount Balrior", "Relic of Nayos",
  "Relic of Nourys", "Relic of Peitha", "Relic of Resistance", "Relic of Reunification",
  "Relic of Rivers", "Relic of Shackles", "Relic of Sorrow", "Relic of Speed",
  "Relic of Surging", "Relic of Thorns", "Relic of Vampirism", "Relic of Vass",
  "Relic of Zakiros", "Relic of the Adventurer", "Relic of the Afflicted", "Relic of the Alliance",
  "Relic of the Aristocracy", "Relic of the Astral Ward", "Relic of the Beehive", "Relic of the Biomancer",
  "Relic of the Blightbringer", "Relic of the Brawler", "Relic of the Cavalier", "Relic of the Centaur",
  "Relic of the Chronomancer", "Relic of the Citadel", "Relic of the Claw", "Relic of the Coral Heart",
  "Relic of the Daredevil", "Relic of the Deadeye", "Relic of the Defender", "Relic of the Demon Queen",
  "Relic of the Dragonhunter", "Relic of the Eagle", "Relic of the Earth", "Relic of the Firebrand",
  "Relic of the First Revenant", "Relic of the Flock", "Relic of the Forest Dweller", "Relic of the Founding",
  "Relic of the Fractal", "Relic of the Golemancer", "Relic of the Herald", "Relic of the Holosmith",
  "Relic of the Ice", "Relic of the Krait", "Relic of the Lich", "Relic of the Living City",
  "Relic of the Midnight King", "Relic of the Mirage", "Relic of the Mist Stranger", "Relic of the Mists Tide",
  "Relic of the Monk", "Relic of the Nautical Beast", "Relic of the Necromancer", "Relic of the Nightmare",
  "Relic of the Ogre", "Relic of the Pack", "Relic of the Phenom", "Relic of the Pirate Queen",
  "Relic of the Privateer", "Relic of the Reaper", "Relic of the Scoundrel", "Relic of the Scourge",
  "Relic of the Sorcerer", "Relic of the Steamshrieker", "Relic of the Stormsinger", "Relic of the Sunless",
  "Relic of the Thief", "Relic of the Trooper", "Relic of the Twin Generals", "Relic of the Unseen Invasion",
  "Relic of the Warrior", "Relic of the Water", "Relic of the Wayfinder", "Relic of the Weaver",
  "Relic of the Wizard's Tower", "Relic of the Zephyrite", "Relic of Galdra", "Relic of Watch",
  "Relic of the Cruel Overseer", "Relic of the Director", "Relic of the Doyen", "Relic of the Sacred Grounds",
] as const;

export const BUILDER_RELIC_IDS: Record<string, number> = {
  "Relic of Agony": 104849,
  "Relic of Akeem": 100432,
  "Relic of Altruism": 104256,
  "Relic of Antitoxin": 100390,
  "Relic of Atrocity": 102245,
  "Relic of Bava Nisos": 104848,
  "Relic of Bloodstone": 104800,
  "Relic of Castora": 105652,
  "Relic of Cerus": 100074,
  "Relic of Dagda": 100942,
  "Relic of Durability": 100455,
  "Relic of Dwayna": 100442,
  "Relic of Evasion": 100614,
  "Relic of Febe": 101116,
  "Relic of Fire": 104501,
  "Relic of Fireworks": 100947,
  "Relic of Fog": 107030,
  "Relic of Geysers": 103763,
  "Relic of Isgarren": 99997,
  "Relic of Karakosa": 101268,
  "Relic of Leadership": 100625,
  "Relic of Lyhr": 100461,
  "Relic of Mabon": 100115,
  "Relic of Mercy": 100429,
  "Relic of Mistburn": 104994,
  "Relic of Mosyn": 101801,
  "Relic of Mount Balrior": 103872,
  "Relic of Nayos": 101198,
  "Relic of Nourys": 101191,
  "Relic of Peitha": 100177,
  "Relic of Resistance": 100794,
  "Relic of Reunification": 103984,
  "Relic of Rivers": 103015,
  "Relic of Shackles": 106916,
  "Relic of Sorrow": 103424,
  "Relic of Speed": 100148,
  "Relic of Surging": 100063,
  "Relic of Thorns": 104424,
  "Relic of Vampirism": 100676,
  "Relic of Vass": 100775,
  "Relic of Zakiros": 101955,
  "Relic of the Adventurer": 100561,
  "Relic of the Afflicted": 100693,
  "Relic of the Alliance": 107192,
  "Relic of the Aristocracy": 100849,
  "Relic of the Astral Ward": 100388,
  "Relic of the Beehive": 103977,
  "Relic of the Biomancer": 106364,
  "Relic of the Blightbringer": 102199,
  "Relic of the Brawler": 100527,
  "Relic of the Cavalier": 100542,
  "Relic of the Centaur": 100385,
  "Relic of the Chronomancer": 100450,
  "Relic of the Citadel": 100448,
  "Relic of the Claw": 103574,
  "Relic of the Coral Heart": 107061,
  "Relic of the Daredevil": 100345,
  "Relic of the Deadeye": 100924,
  "Relic of the Defender": 100934,
  "Relic of the Demon Queen": 101166,
  "Relic of the Dragonhunter": 100090,
  "Relic of the Eagle": 104241,
  "Relic of the Earth": 100435,
  "Relic of the Firebrand": 100453,
  "Relic of the First Revenant": 105585,
  "Relic of the Flock": 99965,
  "Relic of the Forest Dweller": 107124,
  "Relic of the Founding": 101737,
  "Relic of the Fractal": 100153,
  "Relic of the Golemancer": 100403,
  "Relic of the Herald": 100219,
  "Relic of the Holosmith": 100908,
  "Relic of the Ice": 100048,
  "Relic of the Krait": 100230,
  "Relic of the Lich": 100238,
  "Relic of the Living City": 104928,
  "Relic of the Midnight King": 101139,
  "Relic of the Mirage": 100158,
  "Relic of the Mist Stranger": 106206,
  "Relic of the Mists Tide": 103901,
  "Relic of the Monk": 100031,
  "Relic of the Nautical Beast": 106920,
  "Relic of the Necromancer": 100580,
  "Relic of the Nightmare": 100579,
  "Relic of the Ogre": 100311,
  "Relic of the Pack": 100752,
  "Relic of the Phenom": 104733,
  "Relic of the Pirate Queen": 106221,
  "Relic of the Privateer": 100479,
  "Relic of the Reaper": 100739,
  "Relic of the Scoundrel": 106355,
  "Relic of the Scourge": 100368,
  "Relic of the Sorcerer": 101863,
  "Relic of the Steamshrieker": 104022,
  "Relic of the Stormsinger": 102595,
  "Relic of the Sunless": 100400,
  "Relic of the Thief": 100916,
  "Relic of the Trooper": 100411,
  "Relic of the Twin Generals": 101767,
  "Relic of the Unseen Invasion": 100694,
  "Relic of the Warrior": 100144,
  "Relic of the Water": 100659,
  "Relic of the Wayfinder": 101943,
  "Relic of the Weaver": 100194,
  "Relic of the Wizard's Tower": 100557,
  "Relic of the Zephyrite": 100893,
  "Relic of Galdra": 109264,
  "Relic of Watch": 109709,
  "Relic of the Cruel Overseer": 109664,
  "Relic of the Director": 109351,
  "Relic of the Doyen": 109522,
  "Relic of the Sacred Grounds": 109267,
};


export const BUILDER_FOOD_CHOICES: BuilderNamedChoice[] = [
  { label: "Peppercorn-Crusted Sous-Vide Steak", id: 91734 },
  { label: "Cilantro Lime Sous-Vide Steak", id: 91805 },
  { label: "Bowl of Sweet and Spicy Butternut Squash Soup", id: 41569 },
  { label: "Plate of Truffle Steak Dinner", id: 12469 },
  { label: "Bowl of Fancy Potato and Leek Soup", id: 12485 },
  { label: "Plate of Beef Rendang", id: 86997 },
  { label: "Plate of Kimchi Pancakes", id: 96578 },
  { label: "Mint-Pear Cured Meat Flatbread", id: 91703 },
  { label: "Clove-Spiced Pear and Cured Meat Flatbread", id: 91784 },
  { label: "Mint and Veggie Flatbread", id: 91727 },
  { label: "Delicious Rice Ball", id: 68634 },
  { label: "Eggs Benedict with Mint-Parsley Sauce", id: 91758 },
  { label: "Bowl of Fruit Salad with Mint Garnish", id: 91690 },
  { label: "Bowl of Seaweed Salad", id: 12471 },
];

export const BUILDER_UTILITY_CHOICES: BuilderNamedChoice[] = [
  { label: "Superior Sharpening Stone", id: 78305 },
  { label: "Furious Sharpening Stone", id: 67530 },
  { label: "Bountiful Sharpening Stone", id: 67531 },
  { label: "Bountiful Maintenance Oil", id: 67528 },
  { label: "Furious Maintenance Oil", id: 67529 },
];

export const BUILDER_RUNE_CHOICES: BuilderNamedChoice[] = [
  { label: "Superior Rune of Altruism", id: 38206 },
  { label: "Superior Rune of Antitoxin", id: 48907 },
  { label: "Superior Rune of Balthazar", id: 24765 },
  { label: "Superior Rune of Divinity", id: 24732 },
  { label: "Superior Rune of Durability", id: 73653 },
  { label: "Superior Rune of Dwayna", id: 24768 },
  { label: "Superior Rune of Evasion", id: 67344 },
  { label: "Superior Rune of Exuberance", id: 44951 },
  { label: "Superior Rune of Fireworks", id: 89999 },
  { label: "Superior Rune of Grenth", id: 24779 },
  { label: "Superior Rune of Hoelbrak", id: 24729 },
  { label: "Superior Rune of Infiltration", id: 24703 },
  { label: "Superior Rune of Leadership", id: 70600 },
  { label: "Superior Rune of Lyssa", id: 24776 },
  { label: "Superior Rune of Melandru", id: 24771 },
  { label: "Superior Rune of Mercy", id: 24708 },
  { label: "Superior Rune of Nature's Bounty", id: 81091 },
  { label: "Superior Rune of Orr", id: 24860 },
  { label: "Superior Rune of Perplexity", id: 44957 },
  { label: "Superior Rune of Radiance", id: 67342 },
  { label: "Superior Rune of Rage", id: 24717 },
  { label: "Superior Rune of Rata Sum", id: 24726 },
  { label: "Superior Rune of Resistance", id: 49460 },
  { label: "Superior Rune of Sanctuary", id: 24857 },
  { label: "Superior Rune of Scavenging", id: 24738 },
  { label: "Superior Rune of Snowfall", id: 68437 },
  { label: "Superior Rune of Speed", id: 24720 },
  { label: "Superior Rune of Strength", id: 24714 },
  { label: "Superior Rune of Surging", id: 76813 },
  { label: "Superior Rune of Svanir", id: 24794 },
  { label: "Superior Rune of the Adventurer", id: 24830 },
  { label: "Superior Rune of the Afflicted", id: 24687 },
  { label: "Superior Rune of the Air", id: 24750 },
  { label: "Superior Rune of the Aristocracy", id: 24845 },
  { label: "Superior Rune of the Baelfire", id: 24854 },
  { label: "Superior Rune of the Berserker", id: 71425 },
  { label: "Superior Rune of the Brawler", id: 24833 },
  { label: "Superior Rune of the Cavalier", id: 83367 },
  { label: "Superior Rune of the Centaur", id: 24788 },
  { label: "Superior Rune of the Chronomancer", id: 73399 },
  { label: "Superior Rune of the Citadel", id: 24741 },
  { label: "Superior Rune of the Daredevil", id: 72852 },
  { label: "Superior Rune of the Deadeye", id: 82791 },
  { label: "Superior Rune of the Defender", id: 67912 },
  { label: "Superior Rune of the Dolyak", id: 24699 },
  { label: "Superior Rune of the Dragonhunter", id: 74978 },
  { label: "Superior Rune of the Druid", id: 70450 },
  { label: "Superior Rune of the Eagle", id: 24723 },
  { label: "Superior Rune of the Earth", id: 24744 },
  { label: "Superior Rune of the Elementalist", id: 24800 },
  { label: "Superior Rune of the Engineer", id: 24812 },
  { label: "Superior Rune of the Fire", id: 24747 },
  { label: "Superior Rune of the Firebrand", id: 83338 },
  { label: "Superior Rune of the Flame Legion", id: 24797 },
  { label: "Superior Rune of the Flock", id: 24696 },
  { label: "Superior Rune of the Forgeman", id: 24851 },
  { label: "Superior Rune of the Golemancer", id: 24785 },
  { label: "Superior Rune of the Grove", id: 24735 },
  { label: "Superior Rune of the Guardian", id: 24824 },
  { label: "Superior Rune of the Herald", id: 76100 },
  { label: "Superior Rune of the Holosmith", id: 82633 },
  { label: "Superior Rune of the Ice", id: 24753 },
  { label: "Superior Rune of the Krait", id: 24762 },
  { label: "Superior Rune of the Lich", id: 24688 },
  { label: "Superior Rune of the Mad King", id: 36044 },
  { label: "Superior Rune of the Mesmer", id: 24803 },
  { label: "Superior Rune of the Mirage", id: 84127 },
  { label: "Superior Rune of the Monk", id: 24842 },
  { label: "Superior Rune of the Necromancer", id: 24806 },
  { label: "Superior Rune of the Nightmare", id: 24848 },
  { label: "Superior Rune of the Ogre", id: 24756 },
  { label: "Superior Rune of the Pack", id: 24702 },
  { label: "Superior Rune of the Privateer", id: 24782 },
  { label: "Superior Rune of the Ranger", id: 24815 },
  { label: "Superior Rune of the Reaper", id: 70829 },
  { label: "Superior Rune of the Rebirth", id: 84171 },
  { label: "Superior Rune of the Renegade", id: 83502 },
  { label: "Superior Rune of the Revenant", id: 69370 },
  { label: "Superior Rune of the Scholar", id: 24836 },
  { label: "Superior Rune of the Scourge", id: 83663 },
  { label: "Superior Rune of the Scrapper", id: 71276 },
  { label: "Superior Rune of the Soulbeast", id: 83964 },
  { label: "Superior Rune of the Spellbreaker", id: 84749 },
  { label: "Superior Rune of the Stars", id: 85713 },
  { label: "Superior Rune of the Sunless", id: 47908 },
  { label: "Superior Rune of the Tempest", id: 76166 },
  { label: "Superior Rune of the Thief", id: 24818 },
  { label: "Superior Rune of the Trapper", id: 67339 },
  { label: "Superior Rune of the Traveler", id: 24691 },
  { label: "Superior Rune of the Trooper", id: 24827 },
  { label: "Superior Rune of the Undead", id: 24757 },
  { label: "Superior Rune of the Warrior", id: 24821 },
  { label: "Superior Rune of the Water", id: 24839 },
  { label: "Superior Rune of the Weaver", id: 83423 },
  { label: "Superior Rune of the Wurm", id: 24791 },
  { label: "Superior Rune of the Zephyrite", id: 88118 },
  { label: "Superior Rune of Thorns", id: 72912 },
  { label: "Superior Rune of Tormenting", id: 44956 },
  { label: "Superior Rune of Vampirism", id: 24711 },
];

export const BUILDER_SIGIL_CHOICES: BuilderNamedChoice[] = [
  { label: "Superior Sigil of Absorption", id: 72872 },
  { label: "Superior Sigil of Accuracy", id: 24618 },
  { label: "Superior Sigil of Agility", id: 72092 },
  { label: "Superior Sigil of Agony", id: 24612 },
  { label: "Superior Sigil of Air", id: 24554 },
  { label: "Superior Sigil of Battle", id: 24601 },
  { label: "Superior Sigil of Benevolence", id: 24584 },
  { label: "Superior Sigil of Blight", id: 67913 },
  { label: "Superior Sigil of Blood", id: 24570 },
  { label: "Superior Sigil of Bloodlust", id: 24575 },
  { label: "Superior Sigil of Bounty", id: 81045 },
  { label: "Superior Sigil of Bursting", id: 44944 },
  { label: "Superior Sigil of Celerity", id: 24865 },
  { label: "Superior Sigil of Centaur Slaying", id: 24645 },
  { label: "Superior Sigil of Chilling", id: 24630 },
  { label: "Superior Sigil of Cleansing", id: 67340 },
  { label: "Superior Sigil of Concentration", id: 72339 },
  { label: "Superior Sigil of Corruption", id: 24578 },
  { label: "Superior Sigil of Cruelty", id: 67341 },
  { label: "Superior Sigil of Debility", id: 24636 },
  { label: "Superior Sigil of Demon Slaying", id: 24664 },
  { label: "Superior Sigil of Demons", id: 24583 },
  { label: "Superior Sigil of Destroyer Slaying", id: 24654 },
  { label: "Superior Sigil of Doom", id: 24609 },
  { label: "Superior Sigil of Draining", id: 70825 },
  { label: "Superior Sigil of Dreams", id: 24681 },
  { label: "Superior Sigil of Earth", id: 24560 },
  { label: "Superior Sigil of Elemental Slaying", id: 24661 },
  { label: "Superior Sigil of Energy", id: 24607 },
  { label: "Superior Sigil of Fire", id: 24548 },
  { label: "Superior Sigil of Force", id: 24615 },
  { label: "Superior Sigil of Frailty", id: 24567 },
  { label: "Superior Sigil of Frenzy", id: 82876 },
  { label: "Superior Sigil of Generosity", id: 38294 },
  { label: "Superior Sigil of Geomancy", id: 24605 },
  { label: "Superior Sigil of Ghost Slaying", id: 24809 },
  { label: "Superior Sigil of Grawl Slaying", id: 24648 },
  { label: "Superior Sigil of Hobbling", id: 24627 },
  { label: "Superior Sigil of Hologram Slaying", id: 91339 },
  { label: "Superior Sigil of Hydromancy", id: 24597 },
  { label: "Superior Sigil of Ice", id: 24555 },
  { label: "Superior Sigil of Icebrood Slaying", id: 24651 },
  { label: "Superior Sigil of Impact", id: 24868 },
  { label: "Superior Sigil of Incapacitation", id: 67343 },
  { label: "Superior Sigil of Justice", id: 24678 },
  { label: "Superior Sigil of Karka Slaying", id: 37912 },
  { label: "Superior Sigil of Leeching", id: 24599 },
  { label: "Superior Sigil of Life", id: 24582 },
  { label: "Superior Sigil of Luck", id: 24591 },
  { label: "Superior Sigil of Mad Scientists", id: 24672 },
  { label: "Superior Sigil of Malice", id: 44950 },
  { label: "Superior Sigil of Mischief", id: 68436 },
  { label: "Superior Sigil of Momentum", id: 49457 },
  { label: "Superior Sigil of Nullification", id: 24572 },
  { label: "Superior Sigil of Ogre Slaying", id: 24655 },
  { label: "Superior Sigil of Paralyzation", id: 24639 },
  { label: "Superior Sigil of Perception", id: 24580 },
  { label: "Superior Sigil of Peril", id: 24621 },
  { label: "Superior Sigil of Purity", id: 24571 },
  { label: "Superior Sigil of Rage", id: 24561 },
  { label: "Superior Sigil of Rending", id: 73532 },
  { label: "Superior Sigil of Renewal", id: 44947 },
  { label: "Superior Sigil of Restoration", id: 24594 },
  { label: "Superior Sigil of Ruthlessness", id: 71130 },
  { label: "Superior Sigil of Serpent Slaying", id: 24658 },
  { label: "Superior Sigil of Severance", id: 84505 },
  { label: "Superior Sigil of Smoldering", id: 24624 },
  { label: "Superior Sigil of Smothering", id: 24675 },
  { label: "Superior Sigil of Sorrow", id: 24684 },
  { label: "Superior Sigil of Speed", id: 24589 },
  { label: "Superior Sigil of Stamina", id: 24592 },
  { label: "Superior Sigil of Strength", id: 24562 },
  { label: "Superior Sigil of the Night", id: 36053 },
  { label: "Superior Sigil of the Stars", id: 86170 },
  { label: "Superior Sigil of Torment", id: 48911 },
  { label: "Superior Sigil of Transference", id: 74326 },
  { label: "Superior Sigil of Undead Slaying", id: 24642 },
  { label: "Superior Sigil of Venom", id: 24632 },
  { label: "Superior Sigil of Vision", id: 24600 },
  { label: "Superior Sigil of Water", id: 24551 },
  { label: "Superior Sigil of Wrath", id: 24667 },
];

export const BUILDER_ENRICHMENT_CHOICES: BuilderNamedChoice[] = [
  { label: "Celebratory Birthday Enrichment", id: 93953 },
  { label: "Experienced Enrichment", id: 39330 },
  { label: "Gilded Enrichment", id: 39331 },
  { label: "Karmic Enrichment", id: 39332 },
  { label: "Koda's Warmth Enrichment", id: 79926 },
  { label: "Magical Enrichment", id: 39333 },
  { label: "Otter's Blessing Enrichment", id: 93798 },
  { label: "Wurm's Experienced Blessing Enrichment", id: 101250 },
  { label: "Wurm's Gilded Blessing Enrichment", id: 101272 },
  { label: "Wurm's Karmic Blessing Enrichment", id: 101126 },
  { label: "Wurm's Magical Blessing Enrichment", id: 101302 },
  { label: "Wurm's WvW Reward Track Blessing Enrichment", id: 101193 },
  { label: "Wurm's WXP Blessing Enrichment", id: 101187 },
  { label: "WvW Reward Track Enrichment", id: 87398 },
  { label: "WxP Enrichment", id: 87417 },
];

function storageAvailable(): boolean {
  return typeof localStorage !== "undefined";
}

export function equipmentItemIds(equipment: BuilderEquipment): number[] {
  const values = [
    ...Object.values(equipment.runes),
    ...Object.values(equipment.sigils).flat(),
    equipment.enrichment,
  ];
  return [...new Set(values.map((value) => Number(value)).filter((id) => Number.isInteger(id) && id > 0))];
}

export function readBuilderItemCache(): Record<number, Gw2Item> {
  if (!storageAvailable()) return {};
  try {
    const parsed = JSON.parse(localStorage.getItem(BUILDER_ITEM_CACHE_KEY) ?? "{}") as Record<string, Gw2Item>;
    return Object.fromEntries(Object.entries(parsed).filter(([, item]) => item && Number.isInteger(item.id))) as Record<number, Gw2Item>;
  } catch {
    return {};
  }
}

function writeBuilderItemCache(items: Record<number, Gw2Item>): void {
  if (!storageAvailable()) return;
  try {
    localStorage.setItem(BUILDER_ITEM_CACHE_KEY, JSON.stringify(items));
  } catch {
    // Item names and icons are progressive enhancement. Raw AxiCode values
    // remain intact if browser storage is unavailable or full.
  }
}

export async function loadBuilderItemsByIds(ids: number[]): Promise<Record<number, Gw2Item>> {
  const uniqueIds = [...new Set(ids.filter((id) => Number.isInteger(id) && id > 0))];
  if (!uniqueIds.length) return {};
  const cached = readBuilderItemCache();
  const missing = uniqueIds.filter((id) => !cached[id]);
  if (missing.length) {
    try {
      const fetched = await fetchGw2Items(missing);
      for (const item of fetched) cached[item.id] = item;
      writeBuilderItemCache(cached);
    } catch {
      // Imported IDs remain authoritative. Cached names can still enhance the
      // sheet when the GW2 API is unavailable, without blocking the editor.
    }
  }
  return Object.fromEntries(uniqueIds.flatMap((id) => cached[id] ? [[id, cached[id]]] : []));
}

export function choiceIsCodecSupported(value: string, choices: readonly string[]): boolean {
  return !value || choices.includes(value);
}
