SaveOutHTML=false
SaveOutCSV=false
SaveOutJSON=true
UploadToDPSReports=false
UploadToWingman=false
SendEmbedToWebhook=false
ParseCombatReplay=true
ParseExtensions=true
DetailledWvW=true
RawTimelineArrays=true
OutLocation=.tmp/capture-validation-v011
